SOURCES =	srcs/main.c \
			srcs/ft_init.c \
			srcs/utils/envgeter.c \
			srcs/parser/ft_get_arg.c\
			srcs/utils/ft_utils.c \
			srcs/parser/ft_parse_arg.c \
			srcs/parser/ft_parser.c \
			srcs/parser/ft_get_cmd.c \
			srcs/parser/ft_parse_echo.c \
			srcs/parser/ft_parse_builtins.c \
			srcs/parser/ft_msg.c \
			srcs/parser/ft_parse_msg.c \
			srcs/parser/ft_spec.c \
			srcs/parser/ft_redir.c \
			srcs/utils/ft_strsplit_space.c \
			srcs/utils/prompts.c \
			srcs/utils/env_variable.c \
			srcs/utils/ft_free.c \
			srcs/utils/ft_utils_parsing.c \
			srcs/utils/ft_strtrim.c \
			srcs/utils/ft_util_parsemsg.c \
			srcs/utils/exit.c \
			srcs/utils/ft_utils_redir.c \
			srcs/commands/commands.c \
			srcs/commands/commands_utils.c \
			srcs/commands/pipe.c \
			srcs/commands/pipe_utils.c \
			srcs/commands/redir_utils.c \
			srcs/built-in/cd/cd.c \
			srcs/built-in/echo/echo.c \
			srcs/built-in/env/env.c \
			srcs/built-in/export/export.c \
			srcs/built-in/export/export_utils.c \
			srcs/built-in/pwd/pwd.c \
			srcs/built-in/utils.c \
			srcs/built-in/unset/unset.c
