name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: setup
      run: echo "env" >> runfile
    - name: setup2
      run: echo "exit" >> runfile
    - name: run
      run: ./minishell < runfile < runfile2
    - name: exit
      run: exit
    - name: final_exit
      run: exit
