name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: setup
      run: echo "echo $PATH" > runfile
    - name: run minishell
      run: ./minishell < runfile
    - name: exit
      run: exit
    - name: final_exit
      run: exit
